import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../component/shared/Header'
import Hero from '../component/shared/Hero'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>final project e-commerce site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/8316bc24a7.js" crossorigin="anonymous"></script>
      </Head>

      <main className={styles.main}>
        <Header/>
        <Hero/>
      
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
