import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Salertype from '../component/Salertype'
import ProductCatagory from '../component/ProductCatagory'
import Navbar from '../component/shared/Navbar'
import SimpleSlider from '../component/shared/SimpleSlider'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import SprBox from '../component/SprBox'
import AllProducts from '../component/AllProducts'
import FassionShop from '../component/FassionShop'
import Testimonial from '../component/Testimonial'
import Brand from '../component/Brand'

export default function Home() {
    return (

        <div className={styles.container}>
            <Head>
                <title>final project e-commerce site</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <script src="https://kit.fontawesome.com/8316bc24a7.js" crossorigin="anonymous"></script>
            </Head>

            <main className={styles.main}>

                <div
                    className='absolute bg-red-50 w-[100%] inset-x-0 top-0  flex-col justify-center  '>
                    <header className=" inset-x-0 top-0 z-50">
                        <Navbar/>
                        <SimpleSlider/>
                    </header>

                    <div className='w-full bg-white flex flex-col  pt-10'>

                        <Salertype/>

                        <SprBox/>

                        <ProductCatagory/>
                      
                        <AllProducts/>

                        <FassionShop/>

                        <Testimonial/>

                        <Brand/>

                        

                    </div>

                  
                </div>

            </main>

            <footer className={styles.footer}></footer>
        </div>

    )
}
